modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/antoninvf/placeableMaxwell/issues"
license = "CC BY 4.0"

[[mods]]
modId = "placeablemaxwell"
version = "${version}"
displayName = "Maxwell the placeable cat"
authors = "Flowyan"
description = '''
Adds Maxwell the placeable cat.
'''
logoFile = "maxwell.png"

[[dependencies.placeablemaxwell]]
modId = "neoforge"
type = "required"
versionRange = "[21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeablemaxwell]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.placeablemaxwell]]
modId = "architectury"
type = "required"
versionRange = "[18.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "placeablemaxwell.mixins.json"
